package org.tat.gginl.api.common;

public enum ReferenceType {

	LIFE_PROPOSAL,

	AGENT_COMMISSION,

	LIFE_CLAIM, LIFE_DIS_CLAIM,

	LIFE_COLLECTION,

	LIFE_BILL_COLLECTION,

	COINSURANCE,

	SNAKEBITEPOLICY,

	LIFE_POLICY,

	MEDICAL_POLICY,

	MEDICAL_BILL_COLLECTION,

	TRAVEL_PROPOSAL,

	MEDICAL_PROPOSAL,

	MEDICAL_RENEWAL_PROPOSAL,

	MEDICAL_CLAIM,

	LIFESURRENDER_PROPOSAL,

	LIFE_PAIDUP_PROPOSAL,

	SHORTTERM_LIFE_PAIDUP_PROPOSAL,

	PA_PROPOSAL,

	PERSON_TRAVEL_PROPOSAL,

	FARMER_PROPOSAL,

	SHORT_ENDOWMENT_LIFE_PROPOSAL,

	SHORT_ENDOWMENT_LIFE_POLICY,

	SHORT_ENDOWMENT_LIFE_BILL_COLLECTION,

	SHORTENDOWMENTLIFESURRENDER_PROPOSAL,

	CRITICAL_ILLNESS_PROPOSAL, CRITICAL_ILLNESS_POLICY, MICRO_HEALTH_PROPOSAL, MICRO_HEALTH_POLICY,

	HEALTH_PROPOSAL, HEALTH_POLICY, CRITICAL_ILLNESS_POLICY_BILL_COLLECTION,

	HEALTH_POLICY_BILL_COLLECTION, STUDENT_LIFE_PROPOSAL, STUDENT_LIFE_POLICY, STUDENT_LIFE_BILL_COLLECTION,
	
	PUBLIC_TERM_LIFE_PROPOSAL

}
